%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.6

-ifndef(protos).
-define(protos, true).

-define(protos_gpb_version, "4.10.6").

-ifndef('LOGINREQUEST_PB_H').
-define('LOGINREQUEST_PB_H', true).
-record('LoginRequest',
        {nome = []              :: iodata() | undefined, % = 1
         password = []          :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('LOGINRESPONSE_PB_H').
-define('LOGINRESPONSE_PB_H', true).
-record('LoginResponse',
        {tipo = 'FABRICANTE'    :: 'FABRICANTE' | 'IMPORTADOR' | 'ERRO' | integer() | undefined % = 1, enum LoginResponse.TipoUtilizador
        }).
-endif.

-ifndef('AUTHOPERATIONREQUEST_PB_H').
-define('AUTHOPERATIONREQUEST_PB_H', true).
-record('AuthOperationRequest',
        {password = []          :: iodata() | undefined, % = 1
         request = undefined    :: protos:'OperationRequest'() | undefined % = 2
        }).
-endif.

-ifndef('OPERATIONREQUEST_PB_H').
-define('OPERATIONREQUEST_PB_H', true).
-record('OperationRequest',
        {nome = []              :: iodata() | undefined, % = 1
         request                :: {producao, protos:'OfertaProducaoRequest'()} | {encomenda, protos:'OfertaEncomendaRequest'()} | undefined % oneof
        }).
-endif.

-ifndef('OPERATIONRESPONSE_PB_H').
-define('OPERATIONRESPONSE_PB_H', true).
-record('OperationResponse',
        {code = 'OK'            :: 'OK' | 'INVALID' | integer() | undefined % = 1, enum OperationResponse.ResponseStatusCode
        }).
-endif.

-ifndef('OFERTAPRODUCAOREQUEST_PB_H').
-define('OFERTAPRODUCAOREQUEST_PB_H', true).
-record('OfertaProducaoRequest',
        {produto = []           :: iodata() | undefined, % = 1
         quantMin = 0           :: integer() | undefined, % = 2, 32 bits
         quantMax = 0           :: integer() | undefined, % = 3, 32 bits
         precoUniMin = 0        :: integer() | undefined, % = 4, 32 bits
         duracaoS = 0           :: integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('OFERTAENCOMENDAREQUEST_PB_H').
-define('OFERTAENCOMENDAREQUEST_PB_H', true).
-record('OfertaEncomendaRequest',
        {fabricante = []        :: iodata() | undefined, % = 1
         produto = []           :: iodata() | undefined, % = 2
         quant = 0              :: integer() | undefined, % = 3, 32 bits
         preco = 0              :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('NOTIFICACAOFERTAPRODUCAO_PB_H').
-define('NOTIFICACAOFERTAPRODUCAO_PB_H', true).
-record('NotificacaOfertaProducao',
        {produto = []           :: iodata() | undefined, % = 1
         quantMin = 0           :: integer() | undefined, % = 2, 32 bits
         quantMax = 0           :: integer() | undefined, % = 3, 32 bits
         precoUniMin = 0        :: integer() | undefined, % = 4, 32 bits
         duracaoS = 0           :: integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('NOTIFICACAORESULTADOSIMPORTADOR_PB_H').
-define('NOTIFICACAORESULTADOSIMPORTADOR_PB_H', true).
-record('NotificacaoResultadosImportador',
        {fabricante = []        :: iodata() | undefined, % = 1
         produto = []           :: iodata() | undefined, % = 2
         quant = 0              :: integer() | undefined, % = 3, 32 bits
         preco = 0              :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('NOTIFICACAORESULTADOSFABRICANTE_PB_H').
-define('NOTIFICACAORESULTADOSFABRICANTE_PB_H', true).
-record('NotificacaoResultadosFabricante',
        {encomendas = []        :: [protos:'OfertaEncomendaRequest'()] | undefined % = 1
        }).
-endif.

-endif.
